# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: cloudian-pv-wp
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteMany
#   storageClassName: cloudian
#   csi:
#     driver: csi.s3.amazonaws.com
#     volumeHandle: backend
#     volumeAttributes:
#       bucket: storage-k8s

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-wp
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disks/ssd1

