apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloudian
provisioner: csi.s3.amazonaws.com
parameters:
  type: s3
  # Replace <YOUR_CLOUDIAN_ENDPOINT> with your Cloudian endpoint URL
  endpoint: http://10.200.3.161
  region: hn  # Replace with your specific region
  bucket: storage-k8s
  accessKeyID: <your>
  secretAccessKey: <your>
