# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: cloudian
# provisioner: csi.s3.amazonaws.com
# parameters:
#   type: s3
#   # Replace <YOUR_CLOUDIAN_ENDPOINT> with your Cloudian endpoint URL
#   endpoint: http://10.200.3.161
#   region: hn  # Replace with your specific region
#   bucket: storage-k8s
#   accessKeyID: <your>
#   secretAccessKey: <your>


apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloudian-storage-class
provisioner: cloudian.com/hyperstore
parameters:
  region: hn
  bucket: my-bucket
  accessKey: 54c18bc8557ded6771c9
  secretKey: JMAXLY+9yHMRmjgtECrxD7pf6LU1ChLOjF/EpK+Y
  endpointUrl: http://10.200.3.161
